site_name: as734x
repo_url: https://github.com/luciodias/as734x
repo_name: luciodias/as734x
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  # logo: assets/logo.png
  # favicon: assets/logo.png

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css

watch:
   - .

plugins:
- macros
- mkdocstrings:
    handlers:
      python:
        paths: [as734x]

# extra:
#   commands:
#     run: notas-musicais